data:
  symbol: BTCUSDT
  interval: 1h
  limit: 500
  timespan: 60days
  allow_offline: true
training:
  sequence_length: 48
  prediction_horizon: 1
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  epochs: 3
  batch_size: 16
  lr: 0.001
  train_split: 0.8
weights:
  inputs:
    close: 1.0
    volume: 0.8
    rsi_14: 1.2
    macd: 1.0
    macd_signal: 0.9
    macd_hist: 1.1
  outputs:
    regression: 0.7
    classification: 0.3
